import Modelo.ply.yacc as yacc
from Modelo.analizadorLexico import *


def p_main(p):
    'MAIN : VAR SUBRUTINAS VARIABLES'
    print("main")

def p_subrutinas(p):
    'SUBRUTINAS : PROCEDURES'
    print("subrutina : procedure")

def p_subrutinas2(p):
    'SUBRUTINAS: FUNCTIONS'
    print("subrutina: function")

def p_subrutinas_empty(p):
    'SUBRUTINAS: empty'
    print("subrutina: lambda")

def p_variables(p):
    'VARIABLES: DEFVARIABLE'
    print("variable: defvariable")

def p_variables(p):
    'VARIABLES: empty'
    print("variable: lambda")

def p_procedures(p):
    'PROCEDURES: PROCEDURE NOMVARIABLE ABRIRPARENTESIS PARAMETRO CERRARPARENTESIS VAR DEFVARIABLE ABRIRLLAVE INSTRUCCIONES CERRARLLAVE'

def p_functions(p):
    'FUNCTIONS: FUNCTION TIPODATO NOMVARIABLE ABRIRPARENTESIS PARAMETRO CERRARPARENTESIS VAR DEFVARIABLE ABRIRLLAVE INSTRUCCIONES CERRARLLAVE RETURN NOMVARIABLE'

def p_defvariable(p):
    'DEFVARIABLE: TIPODATO NOMVARIABLE MASVARIABLES'

def p_defvariable2(p):
    'DEFVARIABLE: TIPODATO NOMVARIABLE ASIGNACION NUMERO MASVARIABLES'

def p_defvariable3(p):
    'DEFVARIABLE: TIPODATO NOMVARIABLE ASIGNACION NOMVARIABLE MASVARIABLES'

def p_defvariable4(p):
    'DEFVARIABLE: TIPODATO NOMVARIABLE OPERADORMATEMATICO NOMVARIABLE MASVARIABLES'

def p_parametro(p):
    'PARAMETRO: MODOPARAMETRO TIPODATO NOMVARIABLE MASPARAMETRO'

def p_parametro2(p):
    'PARAMETRO: MODOPARAMETRO TIPODATO ESTRUCTURA MASPARAMETRO'

def p_instrucciones(p):
    'INSTRUCCIONES: DEFVARIABLE'

def p_instrucciones2(p):
    'INSTRUCCIONES: ACCIONES'

def p_instrucciones3(p):
    'INSTRUCCIONES: INSTRUCCIONCON'

def p_instrucciones4(p):
    'INSTRUCCIONES: EMPTY'

def p_masvariables(p):
    'MASVARIABLES: COMA DEFVARIABLE'

def p_masvariables2(p):
    'MASVARIABLES: EMPTY'

def p_masparametro(p):
    'MASPARAMETRO: COMA PARAMETRO'

def p_masparametro2(p):
    'MASPARAMETRO: EMPTY'

def p_estructura(p):
    'ESTRUCTURA: ABRIRCORCHETE DIMENSION CERRARCORCHETE'

def p_acciones(p):
    'ACCIONES: CONDICIONAL'

def p_acciones2(p):
    'ACCIONES: CICLO'

def p_acciones3(p):
    'ACCIONES: LLAMADOSUBRUTINA'

def p_acciones4(p):
    'ACCIONES: WRITE'

def p_acciones5(p):
    'ACCIONES: EMPTY'

def p_dimension(p):
    'DIMENSION: NUMERO MASNUMERO'

def p_condicional(p):
    'CONDICIONAL: IF ABRIRPARENTESIS CONDICION CERRARPARENTESIS THEN INSTRUCCIONES ENDIF'

def p_condicional2(p):
    'CONDICIONAL: IF ABRIRPARENTESIS CONDICION CERRARPARENTESIS THEN INSTRUCCIONES ELSE INSTRUCCIONES ENDIF'

def p_condicional3(p):
    'CONDICIONAL: IF ABRIRPARENTESIS CONDICION CERRARPARENTESIS OPERADORLOGICO ABRIRPARENTESIS CONDICION CERRARPARENTESIS THEN INSTRUCCIONES ENDIF'

def p_condicional4(p):
    'CONDICIONAL: IF ABRIRPARENTESIS CONDICION CERRARPARENTESIS OPERADORLOGICO ABRIRPARENTESIS CONDICION CERRARPARENTESIS THEN INSTRUCCIONES ELSE INSTRUCCIONES ENDIF'

def p_condicional5(p):
    'CONDICIONAL: CASE_OF NOMVARIABLE NUMERO DOSPUNTOS INSTRUCCIONES DEFAULT DOSPUNTOS INSTRUCCIONES ENDCASE'

def p_ciclo(p):
    'CICLO: FOR NOMVARIABLE ASIGNACION NOMVARIABLE TO NOMVARIABLE DO INSTRUCCIONES ENDFOR'

def p_ciclo2(p):
    'CICLO: FOR NUMERO ASIGNACION NUMERO TO NUMERO DO INSTRUCCIONES ENDFOR'

def p_ciclo3(p):
    'CICLO: FOR NOMVARIABLE ASIGNACION NOMVARIABLE TO NOMVARIABLE OPERADORLOGICO NOMVARIABLE DO INSTRUCCIONES ENDFOR'

def p_ciclo4(p):
    'CICLO: FOR NUMERO ASIGNACION NUMERO TO NUMERO OPERADORLOGICO NUMERO DO INSTRUCCIONES ENDFOR'

def p_ciclo5(p):
    'CICLO: FOR NOMVARIABLE ASIGNACION NUMERO TO NOMVARIABLE OPERADORLOGICO NOMVARIABLE DO INSTRUCCIONES ENDFOR'

def p_ciclo6(p):
    'CICLO: FOR NOMVARIABLE ASIGNACION NOMVARIABLE TO NOMVARIABLE OPERADORMATEMATICO NOMVARIABLE DO INSTRUCCIONES ENDFOR'

def p_ciclo7(p):
    'CICLO: FOR NUMERO ASIGNACION NUMERO TO NUMERO OPERADORMATEMATICO NUMERO DO INSTRUCCIONES ENDFOR'

def p_ciclo8(p):
    'CICLO: FOR NOMVARIABLE ASIGNACION NOMVARIABLE DOWNTO NOMVARIABLE INC NUMERO DO INSTRUCCIONES ENDFOR'

def p_ciclo9(p):
    'CICLO: FOR NUMERO ASIGNACION NUMERO DOWNTO NUMERO INC NUMERO DO INSTRUCCIONES ENDFOR'

def p_ciclo10(p):
    'CICLO: FOR NOMVARIABLE ASIGNACION NOMVARIABLE DOWNTO NOMVARIABLE INC NUMERO OPERADORLOGICO NOMVARIABLE DO INSTRUCCIONES ENDFOR'

def p_ciclo11(p):
    'CICLO: FOR NUMERO ASIGNACION NUMERO DOWNTO NUMERO INC NUMERO OPERADORLOGICO NUMERO DO INSTRUCCIONES ENDFOR'

def p_ciclo12(p):
    'CICLO: FOR NOMVARIABLE ASIGNACION NUMERO DOWNTO NOMVARIABLE INC NUMERO OPERADORLOGICO NOMVARIABLE DO INSTRUCCIONES ENDFOR'

def p_ciclo13(p):
    'CICLO: FOR NOMVARIABLE ASIGNACION NOMVARIABLE DOWNTO NOMVARIABLE INC NUMERO OPERADORMATEMATICO NOMVARIABLE DO INSTRUCCIONES ENDFOR'

def p_ciclo14(p):
    'CICLO: FOR NUMERO ASIGNACION NUMERO DOWNTO NUMERO INC NUMERO OPERADORMATEMATICO NUMERO DO INSTRUCCIONES ENDFOR'


